apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  type: NodePort
  selector:
    app: airflow
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow-webserver
          image: apache/airflow:2.1.2
          command: ["airflow", "webserver"]
          envFrom:
            - configMapRef:
                name: airflow-config
          ports:
            - containerPort: 8080
        - name: airflow-scheduler
          image: apache/airflow:2.1.2
          command: ["airflow", "scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-config