apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter
          image: jupyter/base-notebook:latest
          envFrom:
            - configMapRef:
                name: jupyter-config
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: jupyter-storage
              mountPath: /home/jovyan/work
      volumes:
        - name: jupyter-storage
          emptyDir: {}