version: '3.8'

services:
  init:
    image: busybox
    command: echo "Initialization complete"
    container_name: init_service
    depends_on:
      - db
      - jupyterhub

  jupyterhub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyterhub_service
    ports:
      - "${JUPYTERHUB_PORT}:8000"
    volumes:
      - ./jupyterhub_data:/srv/jupyterhub
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/hub/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:13
    container_name: db_service
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:
    name: jupyterhub_network

volumes:
  db_data:
  jupyterhub_data:
